version: "3"

services:

  db:
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rpg
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - net

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    networks:
      - net
    ports:
      - 80:80
    environment:
      PMA_HOST: db:3306
      MYSQL_ROOT_PASSWORD: root

networks:
  net:

volumes:
  db_data: